import { BaseModel } from "./BaseModel";
import { ContentTypes } from "./ContentTypes";
export class ContentPlans extends BaseModel {

		public id!: number;
		public name!: string;
		public plan_template!: string;
		public plan_description!: string;
		public contents!: string;
		public monthly_cents!: number;
		public available!: boolean;
		public buildings_count!: number;
		public characters_count!: number;
		public conditions_count!: number;
		public continents_count!: number;
		public countries_count!: number;
		public creatures_count!: number;
		public deities_count!: number;
		public floras_count!: number;
		public foods_count!: number;
		public governments_count!: number;
		public groups_count!: number;
		public items_count!: number;
		public jobs_count!: number;
		public landmarks_count!: number;
		public languages_count!: number;
		public locations_count!: number;
		public lores_count!: number;
		public magics_count!: number;
		public planets_count!: number;
		public races_count!: number;
		public religions_count!: number;
		public scenes_count!: number;
		public sports_count!: number;
		public technologies_count!: number;
		public towns_count!: number;
		public traditions_count!: number;
		public universes_count!: number;
		public vehicles_count!: number;
		public created_by!: number;
		public created_date!: Date;
		public plan_contents!: ContentTypes[];
		public is_currentPlan!:boolean;
}
