export class Countries {

		public procedureName? : string;
		public id? : string;
		public Tags? : string;
		public Name? : string;
		public Description? : string;
		public Other_Names? : string;
		public Universe? : string;
		public Landmarks? : string;
		public Locations? : string;
		public Towns? : string;
		public Bordering_countries? : string;
		public Education? : string;
		public Governments? : string;
		public Religions? : string;
		public Languages? : string;
		public Sports? : string;
		public Architecture? : string;
		public Music? : string;
		public Pop_culture? : string;
		public Laws? : string;
		public Currency? : string;
		public Social_hierarchy? : string;
		public Population? : string;
		public Area? : string;
		public Crops? : string;
		public Climate? : string;
		public Creatures? : string;
		public Flora? : string;
		public Established_year? : string;
		public Notable_wars? : string;
		public Founding_story? : string;
		public Private_Notes? : string;
		public Notes? : string;
		public created_at? : string;
		public updated_at? : string;
		public user_id? : string;
}
