export class Magics {

		public procedureName? : string;
		public id? : string;
		public Tags? : string;
		public Name? : string;
		public Description? : string;
		public Type_of_magic? : string;
		public Universe? : string;
		public Effects? : string;
		public Visuals? : string;
		public Aftereffects? : string;
		public Conditions? : string;
		public Scale? : string;
		public Negative_effects? : string;
		public Neutral_effects? : string;
		public Positive_effects? : string;
		public Deities? : string;
		public Element? : string;
		public Materials_required? : string;
		public Skills_required? : string;
		public Education? : string;
		public Resource_costs? : string;
		public Limitations? : string;
		public Private_notes? : string;
		public Notes? : string;
		public created_at? : string;
		public updated_at? : string;
		public user_id? : string;
}
