export class Religions {

		public procedureName? : string;
		public id? : string;
		public Tags? : string;
		public Name? : string;
		public Description? : string;
		public Other_Names? : string;
		public Universe? : string;
		public Notable_figures? : string;
		public Origin_story? : string;
		public Artifacts? : string;
		public Places_of_worship? : string;
		public Vision_of_paradise? : string;
		public Obligations? : string;
		public Worship_services? : string;
		public Prophecies? : string;
		public Teachings? : string;
		public Deities? : string;
		public Initiation_process? : string;
		public Rituals? : string;
		public Holidays? : string;
		public Traditions? : string;
		public Practicing_locations? : string;
		public Practicing_races? : string;
		public Private_notes? : string;
		public Notes? : string;
		public created_at? : string;
		public updated_at? : string;
		public user_id? : string;
}
