export class Traditions {

		public procedureName? : string;
		public id? : string;
		public Universe? : string;
		public Alternate_names? : string;
		public Tags? : string;
		public Name? : string;
		public Description? : string;
		public Type_of_tradition? : string;
		public Countries? : string;
		public Dates? : string;
		public Groups? : string;
		public Towns? : string;
		public Gifts? : string;
		public Food? : string;
		public Symbolism? : string;
		public Games? : string;
		public Activities? : string;
		public Etymology? : string;
		public Origin? : string;
		public Significance? : string;
		public Religions? : string;
		public Notable_events? : string;
		public Notes? : string;
		public Private_Notes? : string;
		public created_at? : string;
		public updated_at? : string;
		public user_id? : string;
}
